project_id = "oyiisjfrcvyuflrrmqhq"

[functions.send-contact-email]
verify_jwt = false

[functions.send-training-enquiry]
verify_jwt = false

[functions.generate-offer-letter]
verify_jwt = false

[functions.send-offer-letter]
verify_jwt = false

[functions.fetch-tech-news]
verify_jwt = false